version: '3.1'

services:
  api:
    container_name: horarios_api
    image: horarios_api:1.0.0
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    command: npm run start
    ports:
      - 3001:3001
    volumes:
      - ./backend:/usr/src/api
      - /usr/src/app/node_modules
    restart: unless-stopped

  ui:
    container_name: horarios_ui
    image: horarios_ui:1.0.0
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    #    command: npm run start
    ports:
      - 80:80
    volumes:
      - ./frontend:/usr/src/ui
      - /usr/src/app/node_modules
    restart: unless-stopped

  db:
    container_name: horarios_db
    image: docker.uclv.cu/postgis/postgis:13-3.2
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass2021
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - horarios_postgres:/var/lib/postgresql/data
      - ./backend/seed:/docker-entrypoint-initdb.d/

  adminer:
    container_name: horarios_adminer_1
    image: docker.uclv.cu/adminer:latest
    restart: always
    ports:
      - 8080:8080

volumes:
  horarios_postgres:
    driver: local

